export const vinylsList = [
  {
    name: "Talkin' bout a revolution",
    category: "folk",
    id: "1Tr",
    isBestSale: true,
    isSpecialOffer: false,
  },
  {
    name: "Promise",
    category: "soul",
    id: "2ab",
    isBestSale: false,
    isSpecialOffer: false,
  },
  {
    name: "Bad",
    category: "pop",
    id: "3sd",
    isBestSale: true,
    isSpecialOffer: false,
  },
  {
    name: "Nevermind",
    category: "rock",
    id: "4kk",
    isBestSale: true,
    isSpecialOffer: true,
  },
  {
    name: "Human",
    category: "folk",
    id: "5pl",
    isBestSale: false,
    isSpecialOffer: false,
  },
  {
    name: "Breakfast in America",
    category: "rock",
    id: "6uo",
    isBestSale: false,
    isSpecialOffer: false,
  },
  {
    name: "Legend",
    category: "reggae",
    id: "7ie",
    isBestSale: false,
    isSpecialOffer: true,
  },
  {
    name: "Exodus",
    category: "reggae",
    id: "8fp",
    isBestSale: true,
    isSpecialOffer: false,
  },
  {
    name: "Curtains call 2",
    category: "rap",
    id: "9vn",
    isBestSale: false,
    isSpecialOffer: false,
  },
];
