export const vinylsList = [
  {
    name: "Talkin' bout a revolution",
    artist: "Tracy Chapman",
    category: "folk",
    id: "1Tr",
    isBestSale: true,
    isSpecialOffer: false,
    rarity: 3,
    cover: "tr_talkin.jpg",
    year: 1988,
  },
  {
    name: "Promise",
    artist: "Sade",
    category: "soul",
    id: "2ab",
    isBestSale: false,
    isSpecialOffer: false,
    rarity: 1,
    cover: "s_promise.jpg",
    year: 1985,
  },
  {
    name: "Bad",
    artist: "Michael Jackson",
    category: "pop",
    id: "3sd",
    isBestSale: true,
    isSpecialOffer: false,
    rarity: 1,
    cover: "mj_bad.jpg",
    year: 1987,
  },
  {
    name: "Nevermind",
    artist: "Nirvana",
    category: "rock",
    id: "4kk",
    isBestSale: true,
    isSpecialOffer: true,
    rarity: 1,
    cover: "n_nevermind.jpg",
    year: 1991,
  },
  {
    name: "Human",
    artist: "Rag'n'Bone Man",
    category: "folk",
    id: "5pl",
    isBestSale: false,
    isSpecialOffer: false,
    rarity: 2,
    cover: "r_human.jpg",
    year: 2017,
  },
  {
    name: "Breakfast in America",
    artist: "Supertramp",
    category: "rock",
    id: "6uo",
    isBestSale: false,
    isSpecialOffer: false,
    rarity: 1,
    cover: "s_breakfast.jpg",
    year: 1979,
  },
  {
    name: "Legend",
    artist: "Bob Marley",
    category: "reggae",
    id: "7ie",
    isBestSale: false,
    isSpecialOffer: true,
    rarity: 1,
    cover: "bm_legend.jpg",
    year: 1984,
  },
  {
    name: "Exodus",
    artist: "Bob Marley",
    category: "reggae",
    id: "8fp",
    isBestSale: true,
    isSpecialOffer: false,
    rarity: 3,
    cover: "bm_exodus.jpg",
    year: 1977,
  },
  {
    name: "Curtains call 2",
    artist: "Eminem",
    category: "rap",
    id: "9vn",
    isBestSale: false,
    isSpecialOffer: false,
    cover: "e_curtain2.jpg",
    year: 2005,
  },
  {
    name: "The Velvet Underground & Nico",
    artist: "Velvet Underground",
    category: "rock",
    id: "",
    isBestSale: false,
    isSpecialOffer: false,
    cover: "vu_underground.jpg",
    year: 1967,
  },
];
